server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kavishalakshan706@gmail.com
    password: tfdrckeeapodpyxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

