server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kavishalakshan706@gmail.com
    password: tfdrckeeapodpyxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update   # use create-drop if you want a fresh schema on every run
    show-sql: true
    properties:
      hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path:
